### ISSUE TITLE
alles veraltet

### ISSUE THREAD

**Issue by RTK** [MazeChaZer/dotfiles#1]
Die Dateien sind veraltet. Bitte aktualisiere doch die Dateien. Danke.

**Comment by RTK** [comment]
Die Dateien wurden immer noch nicht aktualisiert.

**Comment by MazeChaZer** [comment]
Das bleibt alles so wies hier ist!

**Comment by RTK** [comment]
Sag mal kannst du auch mal sachlich bleiben?
